services:
  app:
    build:
      context: ./docker/php
    container_name: api-book-notes-php
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - db
    networks:
      api-book-notes:
        aliases:
          - php-fpm

  webserver:
    image: nginx:alpine
    container_name: api-book-notes-nginx
    restart: unless-stopped
    ports:
      - "8000:81"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - api-book-notes
    depends_on:
      - app

  db:
    image: postgres
    environment:
      POSTGRES_DB: book-notes
      POSTGRES_USER: api-user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    networks:
      - api-book-notes

networks:
  api-book-notes:
    driver: bridge

volumes:
  db:
  app-data:
    driver: local
